import java.util.Vector;

public class Grid {

    private int width;
    private int height;

    private final Vector<String> lines = new Vector<String>();

    public Grid(int width, int height) {
        this.width = width;
        this.height = height;

        if(this.width >= 27)
            this.width = 26;
        else if(this.width <= 0)
            this.width = 1;

        if(this.height >= 10)
            this.height = 9;
        else if(this.height <= 0)
            this.height = 1;

        /* Fill the grid */
        // For every column
        for (int i = 0; i < this.width; i++) {
            // Add what is generated by the fillGrid() method
            lines.add(fillGrid());
        }
    }

    private String fillGrid() {
        StringBuilder line = new StringBuilder();

        // For every line
        for(int i = 0; i < this.height; i++) {
            // Generate either true or false
            boolean circle = Math.random() <= 0.5;
            if(circle)
                line.append("[O]");
            else
                line.append("[X]");
        }

        return line.toString();
    }

    public void printGrid() {
        System.out.println("  " + " A  B  C  D  E  F  G  H  I  J  K  L  M  N  O  P  Q  R  S  T  U  V  W  X  Y  Z".substring(0, this.width * 3));
        for(int i = 0; i < lines.size(); i++)
        {
            System.out.println(i + 1  + " " + lines.get(i));
        }
        System.out.println("\n");
    }

    public boolean isCircleFilled() {
        for (String line : lines)
            if(line.contains("X"))
                return false;

        return true;
    }

    public void flipCoin(int x, int y) {
        for(int i = x -1 ; i >= 0; i--) {
            for(int j = y - 1; j >= 0; j--) {
                String line = lines.get(j);
                // Every three characters starting at the second exchange X and O
                if(line.charAt(i * 3 + 1) == 'X')
                    line = line.substring(0, i * 3 + 1) + 'O' + line.substring(i * 3 + 2);
                else
                    line = line.substring(0, i * 3 + 1) + 'X' + line.substring(i * 3 + 2);

                lines.set(j, line);
            }
        }
    }
}
